---
######################################################################
#               !!! fetch_inc.yml !!!                                #
# Function:                                                          #
#   - Search for incident assigned to group,return specific fields   #
#                                                                    #
######################################################################

- name: Search for incident assigned to group, return specific fields
  servicenow.servicenow.snow_record_find:
    username: "{{ snow_user }}"
    password: "{{ snow_passwd }}"
    instance: "{{ snow_instance }}"
    display_value: true
    table: incident
    query: "{{snow_query}}"
    return_fields:
      - number
      - comments_and_work_notes
      - sys_updated_by
  register: ticket

- debug:
     msg: "{{ticket}}"

- set_fact:
     tickets: "{{ticket.record}}"
