---
##################################################################
#                                                                #
#      If any aliases are found for the host record,
#      Network team will get approval from user and run this playbook#

#      This playbook will delete DNS host record from Infoblox
#      and update the status based on success or failure.
#                                                                #
##################################################################
- name: Host record deletion from infoblox post approval
  hosts: localhost
  gather_facts: no
  tasks:
     - include_role:
        name: hostdelete_postapproval                          
       vars:
          infoblox_host: "{{infoblox_host}}" 
          hostRecord: "{{item}}"
          user: "{{ansible_user}}"
          passwd: "{{ansible_password}}"
       loop: "{{host_name.split(',')}}"
       no_log: true
       
     - set_fact:
         final_flist: ""
         final_slist: ""
       
     - set_fact:
         final_flist: "{{failure_list|to_nice_yaml|indent(4)}}"
       when: failure_list is defined
       
     - set_fact:
         final_slist: "{{success_list|to_nice_yaml|indent(4)}}" 
       when: success_list is defined    

     - name: Set metering metric "list_of_hosts"
       set_stats:
        data: 
          list_of_hosts: "{{toil_success_list | unique}}"
        per_host: no
       when: toil_success_list is defined

     - name: Set metering metric "list_of_hosts"
       set_stats:
          data: 
            list_of_hosts: []
          per_host: no
       when: toil_success_list is not defined
        
     - name: Send mail to the network team with the final message
       community.general.mail:
          host: "{{mail_server}}"
          port: "{{mail_port}}"
          subject: "{{changeNumber}} - DNS Host record deletion Automation Report"
          body: |
                 *******************AUTOMATED MAIL - PLEASE DO NOT REPLY**********************
                   Hi Team,

                   Please find the DNS Host record deletion automation final report.

                   Successful Hosts:
                     {{final_slist}}

                   Failed Hosts:
                     {{final_flist}}
          from: "{{From_mailaddress}}"
          to: "{{To_mailaddress}}"
