---
###################################################################################
# Usecase Name: Listserv LIst deletion
# Playbook description: This playbook will fetch the SR tickets from ServiceNow  
#                       and call the main playbook to process indivdual tickets.
# Version: v1.0
###################################################################################
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Fetch the service request tickets
    block:
    - include_role: 
        name: Listserv_list_deletion
        tasks_from: fetch_sr_details
    - name: Total fetched SCTASKs details 
      debug:
        msg: "{{ tickets }}"
      when: tickets != []
     
    - debug:
        msg: "No Service request found"
      when: tickets == [] 
    - name: success ticket list
      set_fact:
        success_tickets: []
    - name: Execute the workflow for each individual tickets
      include_role: 
        name: Listserv_list_deletion
        tasks_from: process_sr_request
      vars:
        sctask: "{{item}}"
      with_items: "{{tickets}}"
      when: tickets != []
    
    - name: print successfully executed tickets
      debug:
        msg: "Success tickets -> {{success_tickets}}"
    - name: set metering matric 
      set_stats:
        data:
          success_ticket_list: "{{success_tickets | unique}}"
        per_host: no
      when: success_tickets is defined and success_tickets != []
      
  
