---

###################################################################################
# Usecase Name: Password Expiry 
# Playbook description: This playbook will call the password expiry and check if there any lan ID password expires or not if there any lan id there it will sent mail
# Version: v1.0
# Developer: Mayur Matey
# Org: Wipro
###################################################################################
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
    - include_role: 
        name: password_expiry
        tasks_from: Password_Expiry
    rescue:
    - name: Update the output if its unable to call the mail playbook 
      set_fact: 
        response_msg: "Error Occured while calling the main playbook "  
