---
###################################################################################
# Usecase Name: Unix TLA Creation
# Playbook description: This playbook will fetch the SR tickets from ServiceNow  
#                       and call the main playbook to process indivdual tickets.
# Version: v1.0
###################################################################################
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
    - include_role: 
        name: unix_tla_creation 
        tasks_from: fetch_sr_details
    - name: Total fetched SCTASKs details 
      debug:
        msg: "{{ tickets }}"
      when: tickets is defined and tickets != []
     
    - debug:
        msg: "No Service request found"
      when: tickets is undefined or tickets == []    

    - name: success ticket list
      set_fact:
        success_tickets: []
        
    - include_role: 
        name: unix_tla_creation   
        tasks_from: process_sr_request
      vars:
        sctask: "{{item}}"
      with_items: "{{tickets}}"
      when: tickets is defined and tickets != [] #(tickets != []) and (flag_value is defined) and (flag_value == true)

    - name: print successfully executed tickets
      debug:
        msg: "Success tickets -> {{success_tickets}}"

    - name: set metering matric 
      set_stats:
        data:
          success_ticket_list: "{{success_tickets | unique}}"
        per_host: no
      when: success_tickets is defined
          
    - name: clearning the inputs of the ticket at the end
      set_fact:
        fetch_list: ""
