---
###################################################################################
# Usecase Name: Unix FSTAB SOLUTION 
# Playbook description: This playbook will fetch the INC tickets from ServiceNow  
#                       for Unix FSTAB, it'll process the INCs 
#                       and perform the defined automation executions.
# Version: v1.0
# Developer: Kajal Kumari(Kajal.kumari11@wipro.com)
###################################################################################
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
    - name: update job details to db 
      include_role:
          name: ansible_db_integration
          tasks_from: update_job_details

    - name: check the ticket status
      include_role:
        name: servicenow_inc
        tasks_from: state_check
      vars:
        inc_no: "{{ticket_data.IncidentNo}}"

    - include_role: 
        name: unix_fstab_solution_db
        tasks_from: process_inc
      when: "'New' in inc_state"
    
    - name: update job status to db 
      include_role:
          name: ansible_db_integration
          tasks_from: update_exec_status
      vars:
        final_status: "{{exec_status}}"
      
