---
###################################################################################
# Usecase Name: VDI Decommision 
# Playbook description: This playbook will open the sctask which we will get from CSV file  
#                       and call the main playbook to process indivdual tickets.
# Version: v1.0
# Developer: Mayur Matey
# Org: Wipro
###################################################################################
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
    - name: success ticket list
      set_fact:
        success_tickets: []

    - include_role: 
        name: VDI_Decomission
        tasks_from: Open_Sctask 

    - include_role: 
        name: VDI_Decomission   
        tasks_from: process_sr_request 
      vars:
        Sctask_detail: "{{item}}"
      with_items: "{{Sctask_details}}" 
      when: Sctask_details != []

    - name: print successfully executed tickets
      debug:
        msg: "Success tickets -> {{success_tickets}}"

    - name: set metering matric 
      set_stats:
        data:
          success_ticket_list: "{{success_tickets | unique}}"
        per_host: no
      when: success_tickets is defined
        
  
