---
######################################################################
#               !!! fetch_sr_details.yml !!!                         #
#                                                                    #
# Function:                                                          #
#   - Search for SCTASKs assigned to group,return specific fields    #
#                                                                    #
#                                                                    #
######################################################################

- name: Search for SR assigned to group, return specific fields
  servicenow.servicenow.snow_record_find:
    username: "{{ snow_user }}"
    password: "{{ snow_passwd }}"
    instance: "{{ snow_instance }}"
    display_value: true
    table: sc_task
    query: "{{snow_query}}"
    return_fields:
      - number
      - u_details      
  register: ticket
  
- set_fact:
    tickets: "{{ticket.record}}"

- include_role: 
    name: servicenow_sctask
    tasks_from: progress
  vars:
    sr_number: "{{sctask.number}}"
    worknotes_msg: "Automation has started working on the ticket. Automation process ID: {{awx_job_id }}"
    sctask: "{{item}}"
  with_items: "{{tickets}}"
  when: tickets is defined and tickets != []