---
##########################################################################
# Description: This playbook will be triggered to process the individual # 
#              tickets with the complete workflow.                       #
##########################################################################

- name: Extracting required inputs from the ticket.
  block:
    - name: setting up the ticket details
      set_fact:
        ticketNo: "{{ticket.number}}"

    - name: pull the required inputs from the ticket 
      set_fact:
        target_host: "{{ticket.short_description.split('SilverPeak // ')[1] | split(' // Warning')| first | trim}}"
        tunnel: "{{ticket.description.split('AlarmSource: ')[1] | split(' :  Desc') | first | trim}}"
    - debug:
        msg: 
          - "{{target_host}}"
          - "{{tunnel}}"
      when: target_host is defined and tunnel is defined and target_host != "" and tunnel != ""

    # To check verify the fetched inputs and update the ticket incase of insufficient data.
    - name: Update insufficient data error on the ticket
      include_role:
        name: servicenow_inc
        tasks_from: failure_worknotes
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Error occured: Insufficient input data, automation is unable to process the incident. \n target_host: {{target_host}} \n tunnel: {{tunnel}}"
      when: target_host is not defined or target_host == "" or tunnel is not defined or tunnel == "" 
  rescue:
    - name: Update unable to read inputs from the ticket error on the ticket
      include_role:
        name: servicenow_inc
        tasks_from: failure_worknotes
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Error occured: Automation is unable to process the ticket, seems like unable to find the device name or tunnel name."

    
- name: incident details
  debug:
    msg: "Processing -> {{ticketNo}}"

- name: start processing the ticket and call the playbook to execute the storage commands.
  block:  
    - name: Calling playbook to execute the commands
      import_tasks: gnoc_average_latency_solution.yml
      # Update the output of the executed commands on the ticket.
    - name: Update the commands output to the ticket worknotes.
      include_role:
        name: servicenow_inc
        tasks_from: work_notes_only
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "{{avg_msg}}"
      when: avg_msg is defined and avg_msg != ""
    - name: Resolve ticket if threshold value is below 700
      include_role:
        name: servicenow_inc
        tasks_from: success
      vars:
        inc_no: "{{ticketNo}}"
        success_closing_note: "Threshold value is below 700ms, so resolving the INC"
        resolve_message: "Threshold value is{{thres}} which is below 700 ms, so resolving the INC"
      when: thres is defined and thres | int < 700  and avg_msg is defined and avg_msg != ""  and target_host is defined and target_host != "" and tunnel is defined and tunnel != ""  
      #Final worknotes on the ticket
    - name: Update the exit worknotes to the ticket
      include_role:
        name: servicenow_inc
        tasks_from: work_notes_only
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Automation has added the below comments, engineer can have a look and proceed further."
      when: thres is defined and thres | int > 700 and avg_msg is defined and avg_msg != ""
    - name: set assign to field as empty
      include_role:
        name: servicenow_inc
        tasks_from: user_assignment
      vars:
        inc_no: "{{ticketNo}}"
        user_assigned_to: ""
      when: thres is not defined or thres | int >700 or avg_msg is not defined or avg_msg == ""
    - name: Adding ticket as successfully executed list for metering
      set_fact:
        success_tickets: "{{success_tickets + [ticketNo]}}"
  when: target_host is defined and target_host != "" 
 
  # To capture the errors in the playbook.
  rescue:
    - name: Update the errors to the ticket in case of unexpected error
      include_role:
        name: servicenow_inc
        tasks_from: failure_worknotes
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Error occured: Automation is unable to process the ticket, hence routing it for manual intervention."
      when: target_host is not defined or target_host == ""
    - name: Trigger email on failure
      include_role:
        name: mail_notification
        tasks_from: failure_mail
      vars:
        ticket_id: "{{ticketNo}}"
- name: set the variables vaules to null
  set_fact:
    ticketNo: ""
    target_host: ""
    tunnel: ""
    latency: ""
    avg_msg: ""
    thres: ""
    
