---
##########################################################################
# Description: This playbook will be triggered to process the individual # 
#              tickets with the complete workflow.                       #
##########################################################################

- name: Extracting required inputs from the ticket.
  block:
    - name: extract ticket number and configuration item from the ticket
      set_fact:
        ticketNo: "{{ticket_data.IncidentNo}}"
    - name:  put ticket in progess
      include_role:
        name: servicenow_inc
        tasks_from: progress
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Automation has started working on the ticket. Automation process id- {{awx_job_id}}"
    - name : fetch inputs from ticket details 
      set_fact:
        target_host: "{{ticket_data.TargetHost}}"
        interface_name: '{{(ticket_data.Description).split("INTERFACE NAME: ")[1] | split("Service Type:") | first | trim }}'

    # To check verify the fetched inputs and update the ticket incase of insufficient data.
    - name: Update insufficient data error on the ticket
      include_role:
        name: servicenow_inc
        tasks_from: failure_worknotes
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Error occured: Insufficient input data, automation is unable to process the incident. \n target_host: {{target_host}} \n interface_name: {{interface_name}}"
      when: (target_host is not defined) or (target_host == "") or (interface_name is not defined) or (interface_name == "")
  rescue:
    - name: Update unable to read inputs from the ticket error on the ticket
      include_role:
        name: servicenow_inc
        tasks_from: failure_worknotes
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Error occured: Automation is unable to process the ticket, seems like unable to find the effected CI hostname or interface name."
    - name: set execution status flag 
      set_fact:
          exec_status: "FAILED"
    
- name: incident details
  debug:
    msg: "Processing -> {{ticketNo}}"

- name: start processing the ticket and call the playbook to execute the storage commands.
  block:
    - name: Calling playbook to execute the commands
      import_tasks: gnoc_network_interface_down.yml

      # Update the output of the executed commands on the ticket.
    - name: Update the commands output to the ticket worknotes.
      include_role:
        name: servicenow_inc
        tasks_from: work_notes_only
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Interface command output: \n{{interface_ot}}"
      when: interface_ot is defined and interface_ot != ""
      #Final worknotes on the ticket
    - name: Update the exit worknotes to the ticket
      include_role:
        name: servicenow_inc
        tasks_from: work_notes_only
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Automation has added the below comments, engineer can have a look and proceed further."
    - name: set assign to field as empty
      include_role:
        name: servicenow_inc
        tasks_from: user_assignment
      vars:
        inc_no: "{{ticketNo}}"
        user_assigned_to: "" 

    - name: set execution status flag 
      set_fact:
          exec_status: "SUCCESS"
      when: exec_status is undefined or exec_status != 'FAILED'
  when: (target_host is defined) and (target_host != "") and (interface_name is defined) or (interface_name != "")
 
  # To capture the errors in the playbook.
  rescue:
    - name: Update the errors to the ticket in case of unexpected error
      include_role:
        name: servicenow_inc
        tasks_from: failure_worknotes
      vars:
        inc_no: "{{ticketNo}}"
        worknotes_msg: "Error occured: Automation is unable to process the ticket, hence routing it for manual intervention."
    - name: Trigger email on failure
      include_role:
        name: mail_notification
        tasks_from: failure_mail
      vars:
        ticket_id: "{{ticketNo}}"
    - name: set execution status flag
      set_fact:
          exec_status: "FAILED" 
      
