- name: Executing Powershell to get to address
  block:
  - win_shell: 
              |
               $ServerName = "{{server}}.ENT.AD.ORGANIZATION.COM" 
                $AppOwnerfile="\\<network_share>\<solutions_path>\MSSQL_USE_CASES\MSSQL_Diskfree_Space\AppOwnerList.csv"
                $InputObjects = @(Import-Csv $AppOwnerfile -ErrorAction Stop);
                $ToAddress= $InputObjects |Where-Object {$_.ServerName -Contains $ServerName} |Select-Object -ExpandProperty Email
                $ToAddress
                
    register: to_address_op
  - name: Set fact of to_address_output
    set_fact:
      to_address_output: "{{ to_address_op.stdout_lines }}"
    when:  to_address_op is defined and to_address_op.stdout_lines != [] 
  
  - name: Set fact of to_address
    set_fact:
      to_address: "{{ lookup('env', 'MSSQL_SUPPORT_EMAILS', default='support.team@organization.com') }}"
    when: to_address_op.stdout_lines == [] 

  - name: Set fact of to_address
    set_fact:
      to_address: "{{ to_address_output | replace('[','') | replace(']','') }}"
    when:  to_address_op is defined and to_address_op.stdout_lines != [] 

  - name: Set fact of to_address error
    set_fact:
      to_address_error: "{{ to_address_op.stderr_lines }}"
    when:  to_address_op is defined and to_address_op.stderr_lines != []   

  - name: Set fact of to_address error
    set_fact:
      to_address_error: "{{ to_address_op.stderr_lines }}"
    when:  to_address_op.msg is defined and to_address_op.msg != ""
    
  - name: Set fact of to_address when error is defined
    set_fact:
      to_address: ""
    when:  to_address_op is defined and to_address_op.stderr_lines != []    
    
  rescue:
  - debug:
      var: "Automation Failed - while fetching the app owner details {{ to_address_op.msg }}"
    when: to_address_op.msg is defined         
