---
###########################################################################
#                          !!Description!! 
# This playbook will be called to process the individual SR tickets.
###########################################################################
- name: fetching inputs from the ticket
  block:
  - set_fact:
      sctaskNo: "{{sctask.number}}"
  
  
  - name: reading LANID, Name and TLA apllication to be added
    set_fact:
      name: "{{sctask.u_details.split('Name:') [1].split('\n')[0].strip()}}"
      login: "{{sctask.u_details.split('Login ID:')[1].split('\n')[0].strip()}}"
      group_names: "{{sctask.u_details.split('Group:')[1].split('\nSpecial')[0].strip()}}"
      short_descr: "{{sctask.short_description}}"

  - name: Setting Partner email id
    set_fact:
      partner_email: "{{login}}@organization.com" 

    # To check verify the fetched inputs and update the ticket incase of insufficient data.
  - name: update the ticket if the inputs are not being pulled properly
    include_role:
      name: servicenow_sctask
      tasks_from: failure_worknotes
    vars:
      sr_number: "{{sctaskNo}}"
      worknotes_msg: "Error occured: Insufficient input data, automation is unable to process the incident."
    when: (name == "") or (login == "") or (group_names == "")
    
  rescue:
    - include_role:
        name: servicenow_sctask
        tasks_from: failure_worknotes
      vars:
        sr_number: "{{sctaskNo}}"
        worknotes_msg: "Error occured: Automation is unable to process the ticket, seems like required input parameters is eighter blank or not in the proper format."
      


# THIS BLOCK IS CHECKING THE AD SERVER REACHABILITY ##
- name: Check the AD server connectivity.
  when: (name != "") and (login != "") and (group_names != "")
  block:
  - wait_for:
      host: "{{hostname}}"
      port: "{{ad_srv_port}}"
      timeout: "{{ad_srv_timeout}}"
    register: connCheck
    
## In case if the AD server is not reachable, it'll put a work notes on ticket and skip it.
  rescue:
  - include_role:
      name: servicenow_sctask
      tasks_from: failure_worknotes
    vars:
      sr_number: "{{sctaskNo}}"
      worknotes_msg: "Automation failed to complete the request, server is not reachable."
      
  - include_role:
      name: unix_tla_creation
      tasks_from: failure_mail
  - fail:
      msg: "AD server is not reachable..."
    
- name: Python script execution block
  when: (name != "") and (login != "") and (group_names != "")
  block:
  - name: Execute python script
    shell: python3 'roles/unix_tla_creation/tasks/unix_tla.py' "{{name}}" "{{login}}" "{{sctaskNo}}" "{{group_names}}" "{{short_descr}}" "{{hostname}}" "{{ansible_user}}" "{{ansible_password}}" "{{gidnumber_conf}}" "{{loginshell_conf}}"
    register: IDM_TLA_Python_output
    no_log: true
    delegate_to: localhost   

  - debug:
      msg: 
        - "Python script output:"
        - "{{IDM_TLA_Python_output}}" 
    when: IDM_TLA_Python_output is success
 
  - name: IDM TLA execution output
    set_fact: 
      IDM_TLA_Execution: "{{IDM_TLA_Python_output.stdout}}"  

  - name: Adding worknotes to the ticket in success scenario
    include_role:
      name: servicenow_sctask
      tasks_from: work_notes_only
    vars:
      sr_number: "{{sctaskNo}}"
      worknotes_msg: "{{IDM_TLA_Execution}} "

      
  - name: Capture failed message
    set_fact:
      failed_msg: "Error in completing the requested task, Please check below error"
    when: ('FAILED VERIFICATION:' in IDM_TLA_Execution) or ('Fail' in IDM_TLA_Execution) or ('auto provision case!' in IDM_TLA_Execution )


    
  - name: In case of any failure, adding a worknotes on the ticket and leaving the ticket for manual intervention.
    include_role:
      name: servicenow_sctask
      tasks_from: failure_worknotes
    vars:
      sr_number: "{{sctaskNo}}"
      worknotes_msg: "{{failed_msg}} \n\n Hence routing the ticket for manual intervention."
    when: failed_msg is defined and failed_msg != "" 

  - name: closing the STASK after successfull execution
    include_role:
      name: servicenow_sctask
      tasks_from: success
    vars:
      sr_number: "{{sctaskNo}}"
      resolve_message: "All the required actions are taken hence closing the STASK"
      success_closing_note: " All the required actions are taken hence closing the STASK "
    when: ('success' in IDM_TLA_Execution) or ('New TLA and Group added' in IDM_TLA_Execution)   

  #Send the instructions mail to the partner, if request gets completed
  - name: sending mail  
    include_role:
      name: unix_tla_creation
      tasks_from: send_mail
    when: ('success' in IDM_TLA_Execution) or ('New TLA and Group added for account' in IDM_TLA_Execution)   

    
  - name: Add ticket to the metering matrix
    when: IDM_TLA_Execution != ""
    set_fact:
      success_tickets: "{{success_tickets + [sctaskNo]}}"       
 
  rescue:
  - name: In case of any failure, adding a worknotes on the ticket and leaving the ticket for manual intervention.
    include_role:
      name: servicenow_sctask
      tasks_from: failure_worknotes
    vars:
      sr_number: "{{sctaskNo}}"
      worknotes_msg: "{{IDM_TLA_Python_output.stderr}}\n\n Automation failed to complete the request. \n Hence routing the ticket for manual intervention"
  

- name: clearning the inputs of the ticket at the end
  set_fact:
    ticketNo: ""
    name: ""
    login: ""
    group_names: ""
    IDM_TLA_Execution: ""
    short_descr: ""
    partner_email: "" 
    IDM_TLA_Execution_output: ""


