     
- name: block to fetch memory process details
  block:
  - name: execute commands to check memory utilization details
    paramiko_ssh_conn:
      host: '{{ target_host }}'
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
      commands: ['show version','show memory','show processes memory','show processes memory sorted']
    register: memory_process
    no_log: true

  - name: memory utilization command output 
    set_fact:
      memory_details: "{{ memory_process.result }}"
    when: memory_process is succeeded
  rescue:
  - name: memory utilization command output for failure
    set_fact:
      memory_details: " Error occured! {{ memory_process.msg }}"